server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  add_header X-Content-Type-Options "nosniff" always;
  add_header Content-Security-Policy "default-src 'none'; img-src 'self'; style-src 'none'" always;

  location = /health {
    access_log off;
    add_header Content-Type text/plain;
    return 200 'ok\n';
  }

  location /media/ {
    try_files $uri =404;
  }

  location / {
    return 404;
  }
}
